server:
  port: 1234

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: long1029zz@gmail.com
    password: wsll zwqa cwwi ktov
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    from: long1029zz@gmail.com

  datasource:
    url: jdbc:postgresql://localhost:5433/notification-service-db
    username: postgres
    password: longthanh04

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.jdbc.time_zone: UTC

jwt:
  secret-key: SH9xiK7S2IdaopOjIdoMPILj0GpRIvkDXminzOh72xQ+opwyXReQkn9eWd7kEH7m
  expiration: 86400000